---
- name: Test NEXUS Playbook
  hosts: switches

  tasks:
  - name: Create VLAN
    nxos_vlans:
       config:
       - vlan_id: "{{ vlan_id }}"
         name: "{{ vlan_name }}"

  - name: Merge provided configuration with device configuration
    nxos_l2_interfaces:
       config:
       - name: "{{ trunk_interface }}"
         trunk:
           native_vlan: 10
           allowed_vlans: "{{ allowed_vlans }}"
       - name: "{{ access_interface }}"
         access:
           vlan: "{{ access_vlan }}"
       state: merged
