# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - name: Extract playbook from the last commit message
        id: get-playbook
        run: |
            COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            PLAYBOOK=$(echo "$COMMIT_MESSAGE" | grep -oE 'playbook[0-9]+\.yml' || echo "")
            echo "COMMIT_MESSAGE=$COMMIT_MESSAGE"
            echo "PLAYBOOK=$PLAYBOOK" >> $GITHUB_ENV

      - name: Display playbook to run
        run: | 
            echo "Running playbook: ${{ env.PLAYBOOK }}"

      - name: Run the specified playbook
        if: env.PLAYBOOK != ''
        run: ansible-playbook ${{ env.PLAYBOOK }} -i inventory.yml -e @vars.yml
